version: "3.2"
services:
  web:
    build:
      context: ./
    volumes:
      - .:/src
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: blus:*
  mongo:
    container_name: mongo
    restart: unless-stopped
    networks:
      - rabbitmq_nodejs
    image: mongo
    command: mongod --port 27017
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_nodejs
networks:
  rabbitmq_nodejs:
    driver: bridge
